framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: message.bus
        buses:
            message.bus:
                middleware:
                    - 'App\Middleware\LoggerMiddleware'

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            # failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Messenger\MessageInterface': messages
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
